version: '3'
services:
  broker:
    build: broker
  auldfellas:
    build: auldfellas
    environment:
      SERVER_HOST: broker
    depends_on:
      - broker
  girlpower:
    build: girlpower
    environment:
      SERVER_HOST: broker
    depends_on:
      - broker
  dodgydrivers:
    build: dodgydrivers
    environment:
      SERVER_HOST: broker
    depends_on:
      - broker
  client:
    build: client
    environment:
      SERVER_HOST: broker
    depends_on:
      - broker
      - auldfellas 
      - girlpower 
      - dodgydrivers

